django_exercise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('monitor.urls', namespace='monitor')),
]

monitor/urls.py
from django.urls import path
from django_filters.views import FilterView
from .filters import MonitoredInterfaceFilter


from .views import (
    MonitoredInterfaceListView,
    add_resource,
    search
)

app_name = 'monitor'

urlpatterns = [

    path('', MonitoredInterfaceListView.as_view(), name='monitor_list'),
    path('add_resource/', add_resource, name='add_resource'),
    path('search/', FilterView.as_view(filterset_class=MonitoredInterfaceFilter,
        template_name='monitor/search.html'), name='search'),

]

monitor/models.py
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.
class BaseCRUDModel(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True

class MonitoredInterface(BaseCRUDModel):
	external_id = models.CharField(max_length=120, null=False, blank=False)
	mac_address = models.CharField(max_length=12, null=False, blank=False, validators=[
							RegexValidator(regex=r"^[A-F0-9:]{12,17}$",
											message="Mac Address is not valid",
											code="invalid_mac_address")])
	ipv4_address = models.GenericIPAddressField(protocol="IPv4", null=False, blank=False)
	interface_name = models.CharField(max_length=50, null=False, blank=False)

	class Meta:
		unique_together = [['mac_address', 'interface_name'],]

	def __str__(self):
		return f'{self.interface_name} on {self.mac_address}'

monitor/forms.py
from django import forms

from .models import (MonitoredInterface)


class AddResourceForm(forms.Form):
    url = forms.URLField(
        label='URL of Resource',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Please enter the URL here'
        })
    )

monitor/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.db.models import Q
import re

import requests

from .forms import (
    AddResourceForm,
)
from .models import MonitoredInterface

from .filters import MonitoredInterfaceFilter

def search(request):
    interface_list = MonitoredInterface.objects.all()
    interface_filter = MonitoredInterfaceFilter(request.GET, queryset=interface_list)
    return render(request, 'monitor/list.html', {'filter': interface_filter})

def add_resource(request):
    template_name = 'monitor/add_resource.html'
    regex_pattern = re.compile("^[A-F0-9:]{12,17}$")
    if request.method == 'GET':
        form = AddResourceForm(request.GET or None)
        messages = []
    elif request.method == 'POST':
        form = AddResourceForm(request.POST)
        monitoredInterface = MonitoredInterface()
        messages = []
        if form.is_valid():
            url = form.cleaned_data['url']
            try:
                response = requests.get(url)
                data = response.json()
                for entry in data:
                    if 'interfaces' in entry.keys():
                        mac_address = str(entry['mac_address'])
                        if ":" in mac_address:
                            mac_address = mac_address.replace(":","")
                        if regex_pattern.match(mac_address):
                            for item in entry['interfaces']:
                                obj, created = MonitoredInterface.objects.update_or_create(
                                    interface_name=item['name'], mac_address=mac_address,
                                    defaults = {'external_id':item['id'], 'ipv4_address':item['ipv4']} 
                                )
                    else:
                        mac_address = str(entry['mac'])
                        if ":" in mac_address:
                            mac_address = mac_address.replace(":","")
                        if regex_pattern.match(mac_address):
                            obj, created = MonitoredInterface.objects.update_or_create(
                                    interface_name=entry['interface'], mac_address=mac_address,
                                    defaults = {'external_id':entry['guid'], 'ipv4_address':entry['address']} 
                                )
                invalid_entries = MonitoredInterface.objects.filter(
                    Q(interface_name__exact='') | Q(mac_address__exact='')| Q(external_id__exact='')
                    | Q(ipv4_address__exact='')) 
                invalid_entries.delete()
                return redirect('monitor:monitor_list')
            except requests.exceptions.RequestException as e:
                messages = ["The URL Resource is not reachable. Please ensure that it is correct"]
    return render(request, template_name, {
        'form': form,
        'messages': messages,
    })

class MonitoredInterfaceListView(generic.ListView):
    model = MonitoredInterface
    context_object_name = 'interfaces'
    template_name = 'monitor/list.html'

    def get_context_data(self, **kwargs):
        context = super(MonitoredInterfaceListView, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        return context

monitor/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <style type="text/css">
        .spacer{
            margin-top:25px;
        }
    </style>
    {% block custom_css %}{% endblock %}
    <title>Django Monitor</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Django Monitor App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'monitor:monitor_list' %}">Full Resource List <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'monitor:add_resource' %}">Add a Resource <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'monitor:search' %}">Search Stored Resources <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row spacer"></div>
        <div class="row offset-2">
            <div class="col-12">
                {% if messages%}
                    {% for i in messages %}
                        <li class="alert alert-danger">{{i}}</li>
                    {% endfor %}
                {% endif %}
                {% block container %}
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% block custom_js %}{% endblock %}
</body>

</html>

monitor/templates/list.html
{% extends "base.html" %}

{% block container %}
<p>Django Based Monitor Application</a>

<p>This app contains the following urls</p>

<ul>
    <li><a href="{% url 'monitor:book_list'%}">Book List</a></li>
    <li><a href="{% url 'monitor:create_book_normal'%}">Add multiple books using normal forms</a></li>
    <li><a href="{% url 'monitor:create_book_model_form'%}">Add multiple books using model forms</a></li>
    <li><a href="{% url 'monitor:create_book_with_authors'%}">Add a book with multiple author, both using model forms</a></li>
</ul>
{% endblock %}

monitor/templates/monitor/add_resource.html
{% extends "base.html" %}

{% block container %}
{% if heading %}
<h3>{{heading}}</h3>
{% endif %}
<form class="form-horizontal" method="POST" action="">
    {% csrf_token %}
<div class="row form-row spacer">
    <div class="col-2">
        <label>{{form.url.label}}</label>
    </div>
    <div class="col-4">
        <div class="input-group">
            {{form.url}}
        </div>
    </div>
</div>
<div class="row spacer">
    <div class="col-4 offset-2">
        <button type="submit" class="btn btn-block btn-primary">Scan Resource</button>
    </div>
</div>
</form>
{% endblock %}

{% block custom_js %}

{% endblock %}

monitor/templates/monitor/list.html
{% extends "base.html" %}

{% block container %}
<table class="table">
    <tr>
        <th>External ID</th>
        <th>MAC Address</th>
        <th>IPv4 Address</th>
        <th>interface Name</th>
        <th>{{ count }} Entries</th>
    </tr>
{% for interface in interfaces %}
    <tr>
        <td>{{interface.external_id}}</td>
        <td>{{interface.mac_address}}</td>
        <td>{{interface.ipv4_address}}</td>
        <td>{{interface.interface_name}}</td>
    </tr>
{% endfor %}
</table>
{% endblock %}

monitor/templates/monitor/search.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block container %}
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Filter</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.mac_address.label_tag }}
          {% render_field filter.form.mac_address class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.interface_name.label_tag }}
          {% render_field filter.form.interface_name class="form-control" %}
        </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
    </div>
  </form>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>External ID</th>
        <th>MAC Address</th>
        <th>Interface Name</th>
        <th>IPv4 Address</th>
      </tr>
    </thead>
    <tbody>
      {% for interface in filter.qs %}
        <tr>
          <td>{{ interface.external_id }}</td>
          <td>{{ interface.mac_address }}</td>
          <td>{{ interface.interface_name }}</td>
          <td>{{ interface.ipv4_address }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}